version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/work
    working_dir: /work
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 63306:3306
    environment:
      TZ: Asia/Tokyo
    hostname: db
