version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: dev-Dockerfile
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    ports:
      - 8080:8080
      - 2345:2345
    volumes:
      - .:/work
    working_dir: /work
    depends_on:
      - db
    command: air

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 63306:3306
    environment:
      TZ: Asia/Tokyo
    hostname: db
